export default {
	discussionUpvotePost: 'discussion-upvote-post',
	discussionUpvoteReply: 'discussion-upvote-reply',
	discussionReply: 'discussion-reply',
	announcement: 'announcement',
	postAtMention: 'post-at-mention',
	threadAtMention: 'thread-at-mention',
	articleCommentReply: 'article-comment-reply',
	articleCommentAtMention: 'article-comment-at-mention',
	articleCommentReplyAtMention: 'article-comment-reply-at-mention',
	messageWallPost: 'message-wall-post',
	messageWallReply: 'message-wall-reply',
	messageWallPostRemoved: 'message-wall-post-removed',
	talkPageMessage: 'talk-page-message',
};
